### ISSUE TITLE
Possible Incorrect Prerelease Bump

### ISSUE THREAD

**Issue by stdavis** [agrc/get-next-version-action#106]
<img width="673" alt="image" src="https://github.com/agrc/get-next-version-action/assets/1326248/8ffadb61-44b0-4565-851b-848ac9b6d842">

This is from https://github.com/agrc/firebase-auth-arcgis-server-proxy

**Comment by steveoh** [comment]
woah, strange. feat certainly should have certainly recent the dev version

**Comment by stdavis** [comment]
Ya. The latest prod release is 1.2.6. So the minor should not have been bumped twice.
